# Generated by Django 2.1 on 2018-11-25 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_contrato+', to=settings.AUTH_USER_MODEL, verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesional_contrato+', to=settings.AUTH_USER_MODEL, verbose_name='profesional'),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_servicio+', to=settings.AUTH_USER_MODEL, verbose_name='cliente'),
        ),
    ]
