# Generated by Django 2.1 on 2018-10-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='apellido')),
                ('age', models.IntegerField(verbose_name='edad')),
                ('active', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=100, verbose_name='activo')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
