# Generated by Django 2.1 on 2018-10-28 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
