# Generated by Django 2.1 on 2018-10-28 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
