# Generated by Django 2.1 on 2018-10-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, choices=[('Programador', 'Programador'), ('Contador', 'Contador'), ('Arquitecto', 'Arquitecto'), ('Carpintero', 'Carpintero'), ('Coreografo/a', 'Coreografo/a'), ('Medico', 'Medico'), ('Entrenador personal', 'Entrenador personal'), ('Herrero', 'Herrero')], max_length=100, null=True, verbose_name='area'),
        ),
    ]
